//CATEGORIES
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

//POSTS
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

//POST
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const UPDATED_POST_SUCCESS = 'UPDATED_POST_SUCCESS';
export const DELETED_POST_SUCCESS = 'DELETED_POST_SUCCESS';

//COMMENTS
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';